---
ansible_user: rocky
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Use ansible_ prefix to avoid reserved variable warnings
ansible_become: true
ansible_become_method: sudo
ansible_become_user: root